### PR TITLE
Update json-report with v0.3.1

### PR DESCRIPTION
**Pull request by apoorvam**

### CODE REVIEW

**Comment by sriv** [comment]
See https://github.com/apoorvam/json-report/issues/6#issuecomment-486044855

If repository transfer is something to do, then I recommend that the links in the PR be updated accordingly.

**Comment by apoorvam** [comment]
@sriv Will do that. Can you give me permission to create new repositories on getgauge-contrib? Thats required to transfer.

**Comment by sriv** [comment]
I don't this the permission is required @apoorvam - you can initialize a transfer, and someone owning `getgauge-contrib` can accept. It should be accepted within 1 day as per https://help.github.com/en/articles/transferring-a-repository#whats-transferred-with-a-repository

**Comment by shubhamsc** [comment]
I Merged this PR for now. Transferring repo can be done later.

**Comment by apoorvam** [comment]
@sriv I followed the same steps. After the step 2 as per that link, I get this error: 
 
Screen Shot 2019-04-25 at 11 38 56 AM

**Comment by apoorvam** [comment]
Screen Shot 2019-04-28 at 6 26 09 PM
Got this from Github support regarding this transfer issue. Can transfer it to your personal account and then transfer to org. Is that fine? @sriv

**Comment by sriv** [comment]
Ugh, that will just cause levels of redirections.

I have created a `json-report` team in getgauge-contrib organization. You have been included as a maintainer. I believe this should allow you to transfer. Let me know if it doesn't work. 

We have been trying to do multiple housekeeping of access, and it has become a task by itself. Sorry about this back and forth :(

**Comment by apoorvam** [comment]
No luck with that @sriv. 

https://help.github.com/en/articles/restricting-repository-creation-in-your-organization

**Comment by sriv** [comment]
I give up. Please transfer the ownership to me, and I'll move it to getgauge-contrib. Note that there is already a team in getgauge-contrib for json-report. That should give you access to help manage the project.

**Pull request merged**
