### PR TITLE
Update webdriveio on js_webdriver

### PR DESCRIPTION
**Pull request by fernandadagostin**
Solving issue #37 - Update webdriveio on js_webdriver to version 5.14.4

### CODE REVIEW

**Comment by fernandadagostin** [comment]
@gaugebot recheck the pull request.

**Comment by fernandadagostin** [comment]
I accepted the contributor license, so please let me know if you need me to do anything else so finish this issue.

**Comment by fernandadagostin** [comment]
@gaugebot recheck the pull request.

**Comment by fernandadagostin** [comment]
@gaugebot recheck the pull request.

**Comment by fernandadagostin** [comment]
@gaugebot recheck the pull request.

**Comment by sriv** [comment]
@fernandadagostin - I do not see your entry in the CLA entries. Have you clicked on the 'I Agree' in the CLA page?

**Comment by fernandadagostin** [comment]
@gaugebot recheck the pull request.

**Comment by fernandadagostin** [comment]
@sriv Hi sriv, I did many times. (every time I did, here show up the comment '@gaugebot recheck the pull request.' in my name. 

- I did this again a few minutes ago.
screencapture-gauge-bot-herokuapp-auth-github-callback-2019-10-09-07_59_09

- After I clicked on the button "Go back"

Do you think that the special character in my name can cause this problem?

**Comment by fernandadagostin** [comment]
@gaugebot recheck the pull request.

**Comment by fernandadagostin** [comment]
It was the special char.
My last name contains ' from D'agostin. 
I changed that in my profile, then it worked.

**Comment by sriv** [comment]
the gaugebot tried to be smart and prevent some SQL injection! Apologies @fernandadagostin - we'll take a look and make sure that it accepts names as they are meant to be.

**Comment by sriv** [comment]
Thanks for the contribution @fernandadagostin

**Pull request merged**
